import Head from "next/head";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import Services from "../components/services";
import Testimonial from "../components/testimonials";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Klenty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Services />
      <Testimonial />
    </div>
  );
}
